echo Creating cache library project...
dotnet new classlib -n IOServer.Logic.Cache

echo Adding Cache project to the solution...
dotnet sln IOServer.sln add IOServer.Logic.Cache/IOServer.Logic.Cache.csproj
